apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-controller
    app.kubernetes.io/part-of: kserve
  name: kserve-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/kserve/kserve-controller@sha256:6f20ac836b8635bac427d00ee5a92e541ccf6994e3e8aed6c1379c629d45b8b2
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
