apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-art-explainer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-art-explainer
    app.kubernetes.io/part-of: kserve
  name: kserve-art-explainer
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: kserve-art-explainer
status:
  loadBalancer: {}
