apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-storage-initializer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-storage-initializer
    app.kubernetes.io/part-of: kserve
  name: kserve-storage-initializer
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-storage-initializer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-storage-initializer
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/kserve/kserve-storage-initializer@sha256:3b537da9ee5c54b9aa7e5cb8313bad711d1bb6c524ce31efb9c3a66c64becee8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
