apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-storage-initializer
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/kserve/kserve-storage-initializer@sha256:3b537da9ee5c54b9aa7e5cb8313bad711d1bb6c524ce31efb9c3a66c64becee8
        name: container-image
        resources: {}
status: {}
