apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-agent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-agent
    app.kubernetes.io/part-of: kserve
  name: kserve-agent
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-agent
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/kserve/kserve-agent@sha256:c8646f3dae2e8506a3e1ad2facef65c12fb43457e302a2dbdbe93313b6a0ff6d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
